feat: update income tax thresholds according to 2022 scale
tseignette/autoentrepreneur pull request #1
Opened 2023-06-01 12:48 UTC by mlbiche

See https://www.service-public.fr/particuliers/vosdroits/F1419

2023-06-05 14:40 UTC, tseignette requested changes
Il manque un `npm run prerender` sinon ça ne sera pas mis à jour sur https://tseignette.github.io/autoentrepreneur/ 🤗

2023-06-05 15:12 UTC, mlbiche commented
@tseignette J'ai pas checkout en local, j'ai fait la PR depuis GitHub. Tu peux le faire rapidement de ton côté ? Sinon je m'en occupe 👍

2023-06-05 15:17 UTC, tseignette commented
> @tseignette J'ai pas checkout en local, j'ai fait la PR depuis GitHub. Tu peux le faire rapidement de ton côté ? Sinon je m'en occupe 👍

Quand je serai de retour en France à la fin du mois

2023-06-06 09:00 UTC, mlbiche commented on package.json
> +  "engines": {
@tseignette La version de webpack est incompatible avec node 18. Je me suis permis de rajouter ça

2023-06-07 09:15 UTC, merged

2023-06-07 09:16 UTC, tseignette commented
Merci pour ta contribution @mlbiche